//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMusicRevolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int album_id { get; set; }
        public string ALBUM_NAME { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
        public string ALBUM_URL { get; set; }
        public string BAND { get; set; }
        public Nullable<int> ARTIST_ID { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual SONG SONG { get; set; }
    }
}
