//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMusicRevolution.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PakMusicRevolutionEntities : DbContext
    {
        public PakMusicRevolutionEntities()
            : base("name=PakMusicRevolutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<published_news> published_news { get; set; }
        public virtual DbSet<SONG> SONGs { get; set; }
    }
}
