//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMusicRevolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class published_news
    {
        public int news_id { get; set; }
        public int artist_id { get; set; }
        public Nullable<System.DateTime> dat { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual news news { get; set; }
    }
}
