//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMusicRevolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONG
    {
        public int SONG_ID { get; set; }
        public string SONG_NAME { get; set; }
        public string SONG_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
        public string SONG_URL { get; set; }
        public string SONG_IMG_URL { get; set; }
        public Nullable<int> ARTIST_ID { get; set; }
        public Nullable<int> ALBUM_ID { get; set; }
        public Nullable<int> GENRE_ID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual genre genre { get; set; }
    }
}
